[DEV]members page
CECOM-CAU/CECOM_Web pull request #30
Opened 2024-02-05 16:02 UTC by sereene

## Summary
members page를 만들었습니다.

## Description
- 각각 멤버 카드(앞면, 뒷면)를 만들었습니다.
- npm install react-card-flip 해서 카드 flip되는 기능을 구현했습니다
- 뒷면에 프로젝트 명 버튼을 누르면 상세 프로젝트 페이지로 가게끔 구현했습니다(아직 상세 프로젝트 페이지는 없어서 링크부분은 비워놨습니다)
- 이름 옆 인스타 깃 아이콘은 제가 그냥 따로 이미지를 찾아서 첨부했는데 이렇게 해도 되는지 잘 모르겠습니다...

2024-02-05 16:11 UTC, lims00 approved these changes
수고하셨어용!

2024-02-05 16:50 UTC, yymin1022 requested changes
코드 잘 봤습니다! 더미데이터 활용해서 수정하는 것만 반영해주시면 괜찮을 것 같네요!

문득 든 생각인데, NavButton으로 Things 내에서 All, Tools, Components 등으로 나누는 메뉴 부분은 `Link`로 URL 자체를 이동시키기보다 State 변수를 하나 두어서 한 페이지 내에서 값만 바꾸어 보여주는게 더 낫지 않을까 싶네요! 왠지 세부적으로 분류하고 나면, 값이 그리 많지 않을 것 같아서 페이지까지 옮기는게 더 비효율일 것 같은데.. 이거는 다음 회의 한번 하면서 다같이 이야기해보아요!

2024-02-10 13:16 UTC, yymin1022 approved these changes
좋습니다!
다음 작업에서 img태그 관련된 한가지 부분만 수정 부탁드립니다!

2024-02-10 13:16 UTC, yymin1022 commented on src/app/members/_components/Backcard.tsx
> +                        <img className={'ml-[-9px] mb-[2px] h-[22px]'} src={member.github} alt="Github"/>
`12`, `13` 라인의 `img` 태그 내에서 `src` 속성값으로 `Member` 데이터의 `instagram`과 `github` 값을 직접 참조하도록 되어있는데, 해당 데이터는 URL정보를 담고있으므로 `img`의 `src`가 아닌 `Link` 태그를 통해 이동할 수 있도록 해야합니다! `img` 태그의 `src` 값으로는 Instagram 및 GitHub의 아이콘을 지정해주시면 됩니다.

나중에 수정해주세요!

2024-02-10 13:16 UTC, merged

2024-02-10 13:26 UTC, sereene commented on src/app/members/_components/Backcard.tsx
> +                        <img className={'ml-[-9px] mb-[2px] h-[22px]'} src={member.github} alt="Github"/>
앗 넵 알겠습니당!!